# -*- coding: utf-8 -*-
"""EPPQ contextual simulator (v11.0 - Termodinâmico)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2mR6_HBKwTSkrclnqE1XTHVEkEV6Nbn
"""

# ============================================================
# EPPQ contextual simulator (v11.0 - Termodinâmico)
# bloco único pronto para Colab
# ============================================================

import io
import copy
import random
from collections import defaultdict
from contextlib import redirect_stdout

import networkx as nx
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

# ============================================================
# CONFIG GLOBAL DO EXPERIMENTO
# ============================================================

N = 30
D_star = 4
R_star = 2

STEPS = 60
SEEDS = [1, 7, 13]
TEMPERATURES = [0.0, 0.3, 0.5, 1.0]

K_moves = 50
K_fiber_local = 10
K_fiber_global = 1
K_fiber_two_layer = 5
eps_stop = 1e-3

L_ctx = 5
rho_star = 0.18
p_local_add = 0.20
macro_hop = 2
macro_rounds = 1

# Troque aqui a condição inicial do grafo:
# "path"   -> caminho simples
# "cycle"  -> ciclo
# "tree"   -> árvore aleatória conexa
# "ws"     -> Watts-Strogatz
# "erdos"  -> Erdos-Renyi, com correção automática de conexidade
START_GRAPH_MODE = "path"

# Modo de execução:
# True  -> roda toda a bateria seed x temperatura
# False -> roda apenas um exemplo simples
RUN_FULL_BATTERY = True

# Se RUN_FULL_BATTERY = False, este exemplo roda:
SAMPLE_SEED = 7
SAMPLE_T = 0.5

# Se True, imprime todas as iterações da dinâmica
SHOW_DETAILED_RUNS = False

# ============================================================
# CONSTRUÇÃO DA CONDIÇÃO INICIAL
# ============================================================

def build_start_graph(N, mode="path", seed=0):
    rng = np.random.default_rng(seed)

    if mode == "path":
        G = nx.path_graph(N)

    elif mode == "cycle":
        G = nx.cycle_graph(N)

    elif mode == "tree":
        G = nx.generators.trees.random_tree(N, seed=seed)

    elif mode == "ws":
        k = 4 if N >= 6 else 2
        if k >= N:
            k = max(2, N - 2)
        G = nx.watts_strogatz_graph(N, k=k, p=0.15, seed=seed)

    elif mode == "erdos":
        p = min(0.15, 3.0 / max(1, N))
        G = nx.erdos_renyi_graph(N, p=p, seed=seed)

    else:
        raise ValueError("START_GRAPH_MODE deve ser: path, cycle, tree, ws ou erdos")

    G = nx.convert_node_labels_to_integers(G)

    if not nx.is_connected(G):
        comps = [list(c) for c in nx.connected_components(G)]
        for i in range(len(comps) - 1):
            a = int(rng.choice(comps[i]))
            b = int(rng.choice(comps[i + 1]))
            G.add_edge(a, b)

    return G

# ============================================================
# UTILIDADES DE MÉTRICA
# ============================================================

def compute_thermal_metrics(df):
    if df is None or len(df) == 0:
        return {
            "E_final": np.nan,
            "E_mean_tail": np.nan,
            "E_std_tail": np.nan,
            "tail_slope": np.nan,
            "uphill_rate_total": np.nan,
            "uphill_rate_tail": np.nan,
            "plateau_var_tail": np.nan,
            "plateau_std_tail": np.nan,
            "burn_in": np.nan,
        }

    energies = df["I_eff"].to_numpy(dtype=float)
    tvals = df["t"].to_numpy(dtype=float)

    burn_in = max(1, len(df) // 2)
    tail = df.iloc[burn_in:].copy()

    if len(energies) >= 2:
        dE = np.diff(energies)
        uphill_rate_total = float(np.mean(dE > 1e-12))
    else:
        uphill_rate_total = np.nan

    if len(tail) >= 2:
        dE_tail = np.diff(tail["I_eff"].to_numpy(dtype=float))
        uphill_rate_tail = float(np.mean(dE_tail > 1e-12))
        coeffs = np.polyfit(
            tail["t"].to_numpy(dtype=float),
            tail["I_eff"].to_numpy(dtype=float),
            1
        )
        tail_slope = float(coeffs[0])
    else:
        uphill_rate_tail = np.nan
        tail_slope = np.nan

    return {
        "E_final": float(energies[-1]),
        "E_mean_tail": float(tail["I_eff"].mean()),
        "E_std_tail": float(tail["I_eff"].std(ddof=1)) if len(tail) > 1 else 0.0,
        "tail_slope": tail_slope,
        "uphill_rate_total": uphill_rate_total,
        "uphill_rate_tail": uphill_rate_tail,
        "plateau_var_tail": float(tail["I_eff"].var(ddof=1)) if len(tail) > 1 else 0.0,
        "plateau_std_tail": float(tail["I_eff"].std(ddof=1)) if len(tail) > 1 else 0.0,
        "burn_in": burn_in,
    }

def run_safely(sim, steps, T, verbose=False):
    if verbose:
        sim.run(steps=steps, T=T)
    else:
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            sim.run(steps=steps, T=T)

# ============================================================
# SIMULADOR
# ============================================================

class EPPQContextualSimulator:
    def __init__(
        self,
        N=30,
        D_star=4,
        R_star=2,
        context_mode="two_layer",   # "local", "global", "two_layer"
        seed=0,
        K_moves=50,
        K_fiber_local=10,
        K_fiber_global=1,
        K_fiber_two_layer=5,
        eps_stop=1e-3,
        L_ctx=None,
        rho_star=0.18,
        p_local_add=0.20,
        macro_hop=2,
        macro_rounds=1,
        start_graph=None,
    ):
        self.N = N if start_graph is None else start_graph.number_of_nodes()
        self.D_star = D_star
        self.R_star = R_star
        self.context_mode = context_mode
        self.seed = seed
        self.rng = random.Random(seed)
        self.np_rng = np.random.default_rng(seed)

        self.K_moves = K_moves
        self.K_fiber_local = K_fiber_local
        self.K_fiber_global = K_fiber_global
        self.K_fiber_two_layer = K_fiber_two_layer
        self.eps_stop = eps_stop

        self.L_ctx = L_ctx if L_ctx is not None else (D_star + 1)
        self.rho_star = rho_star
        self.p_local_add = p_local_add
        self.macro_hop = macro_hop
        self.macro_rounds = macro_rounds

        # pesos do funcional
        self.l_var = 5.0
        self.l_deg = 10.0
        self.l_ctx = 1.0
        self.l_ctx_macro = 0.8
        self.l_coh = 0.25
        self.l_dens = 5.0
        self.l_glue = 2.0
        self.l_carry = 0.1

        self.S = start_graph.copy() if start_graph is not None else nx.path_graph(self.N)
        self.history = []
        self.diag = defaultdict(list)

    # --------------------------------------------------------
    # admissibilidade
    # --------------------------------------------------------
    def Psi(self, S):
        if not nx.is_connected(S):
            return False
        degs = dict(S.degree()).values()
        if len(degs) == 0:
            return False
        if max(degs) > self.D_star:
            return False
        return True

    # --------------------------------------------------------
    # bolas locais
    # --------------------------------------------------------
    def local_restriction_nodes(self, S, v, Rc=None):
        if Rc is None:
            Rc = self.R_star
        return list(nx.single_source_shortest_path_length(S, v, cutoff=Rc).keys())

    # --------------------------------------------------------
    # geradores de contexto
    # --------------------------------------------------------
    def generate_gamma_local(self, S):
        G = nx.Graph()
        G.add_nodes_from(S.nodes())
        G.add_edges_from(S.edges())

        nodes = list(S.nodes())
        n_trials = max(1, self.N // 2)

        for _ in range(n_trials):
            v = self.rng.choice(nodes)
            ball = self.local_restriction_nodes(S, v, self.R_star)
            if len(ball) < 2:
                continue
            if self.rng.random() < self.p_local_add:
                u, w = self.rng.sample(ball, 2)
                if u != w and not G.has_edge(u, w):
                    G.add_edge(u, w, length=1.0)

        return G

    def generate_gamma_global(self, S):
        dist = dict(nx.all_pairs_shortest_path_length(S))
        G = nx.Graph()
        G.add_nodes_from(S.nodes())

        for u in S.nodes():
            for v in S.nodes():
                if u < v and v in dist[u]:
                    d = dist[u][v]
                    if d <= self.L_ctx:
                        G.add_edge(u, v, length=float(d))

        return G

    def densify_macro(self, G_micro):
        H = G_micro.copy()
        for _ in range(self.macro_rounds):
            new_edges = set()
            for u in H.nodes():
                lengths = nx.single_source_shortest_path_length(H, u, cutoff=self.macro_hop)
                for v, d in lengths.items():
                    if u < v and 1 < d <= self.macro_hop:
                        new_edges.add((u, v))
            if not new_edges:
                break
            H.add_edges_from(new_edges)
        return H

    def generate_gamma_two_layer(self, S):
        G_micro = self.generate_gamma_local(S)
        rho_micro = nx.density(G_micro) if G_micro.number_of_nodes() > 1 else 0.0

        if rho_micro >= self.rho_star:
            G_macro = self.densify_macro(G_micro)
            regime = "macro"
        else:
            G_macro = G_micro.copy()
            regime = "micro"

        return {
            "micro": G_micro,
            "macro": G_macro,
            "rho_micro": rho_micro,
            "rho_macro": nx.density(G_macro) if G_macro.number_of_nodes() > 1 else 0.0,
            "regime": regime,
        }

    def fiber(self, S):
        if self.context_mode == "local":
            return [self.generate_gamma_local(S) for _ in range(self.K_fiber_local)]
        elif self.context_mode == "global":
            return [self.generate_gamma_global(S) for _ in range(self.K_fiber_global)]
        elif self.context_mode == "two_layer":
            return [self.generate_gamma_two_layer(S) for _ in range(self.K_fiber_two_layer)]
        else:
            raise ValueError("context_mode must be 'local', 'global', or 'two_layer'")

    # --------------------------------------------------------
    # compatibilidade
    # --------------------------------------------------------
    def edge_set(self, G):
        return {tuple(sorted(e)) for e in G.edges()}

    def raw_mismatch(self, S, Gamma, Rc=None):
        if Rc is None:
            Rc = self.R_star

        total = 0
        for v in S.nodes():
            nodes = self.local_restriction_nodes(S, v, Rc)
            subS = S.subgraph(nodes)
            subG = Gamma.subgraph(nodes)

            edges_S = self.edge_set(subS)
            edges_G = self.edge_set(subG)

            total += len(edges_S.symmetric_difference(edges_G))

        return float(total)

    def mismatch(self, S, Gamma, Rc=None, normalized=True):
        raw = self.raw_mismatch(S, Gamma, Rc=Rc)
        if normalized:
            return raw / max(1, S.number_of_nodes())
        return raw

    def context_coherence(self, G_micro, G_macro):
        e_micro = self.edge_set(G_micro)
        e_macro = self.edge_set(G_macro)
        raw = len(e_micro.symmetric_difference(e_macro))
        norm = raw / max(1, G_micro.number_of_nodes())
        return float(norm), float(raw)

    # --------------------------------------------------------
    # termos energéticos
    # --------------------------------------------------------
    def variance_penalty(self, S):
        degs = np.array(list(dict(S.degree()).values()))
        return float(np.var(degs)) if len(degs) > 0 else 0.0

    def degree_penalty(self, S):
        return float(sum(max(0, d - self.D_star) ** 2 for d in dict(S.degree()).values()))

    def geo(self, G):
        try:
            return float(nx.average_shortest_path_length(G))
        except Exception:
            return 100.0

    def carry(self, S_old, S_new):
        return float(len(self.edge_set(S_old).symmetric_difference(self.edge_set(S_new))))

    def interface_terms(self, S, Gamma, S_old):
        terms = {
            "var": self.variance_penalty(S),
            "deg": self.degree_penalty(S),
            "carry": self.carry(S_old, S),
        }

        if isinstance(Gamma, dict):
            Gm = Gamma["micro"]
            Gc = Gamma["macro"]

            ctx_micro_norm = self.mismatch(S, Gm, self.R_star, normalized=True)
            ctx_micro_raw = self.raw_mismatch(S, Gm, self.R_star)

            ctx_macro_norm = self.mismatch(S, Gc, self.R_star, normalized=True)
            ctx_macro_raw = self.raw_mismatch(S, Gc, self.R_star)

            coh_norm, coh_raw = self.context_coherence(Gm, Gc)
            dens_pen = max(0.0, self.rho_star - Gamma["rho_micro"])

            terms.update({
                "ctx_micro": ctx_micro_norm,
                "ctx_micro_raw": ctx_micro_raw,
                "ctx_macro": ctx_macro_norm,
                "ctx_macro_raw": ctx_macro_raw,
                "coherence": coh_norm,
                "coherence_raw": coh_raw,
                "dens_pen": dens_pen,
                "rho_micro": Gamma["rho_micro"],
                "rho_macro": Gamma["rho_macro"],
                "regime_code": 1.0 if Gamma["regime"] == "macro" else 0.0,
                "geo": self.geo(Gc),
            })

            energy = (
                self.l_var * terms["var"]
                + self.l_deg * terms["deg"]
                + self.l_ctx * terms["ctx_micro"]
                + self.l_ctx_macro * terms["ctx_macro"]
                + self.l_coh * terms["coherence"]
                + self.l_dens * terms["dens_pen"]
                + self.l_glue * terms["geo"]
                + self.l_carry * terms["carry"]
            )
        else:
            G = Gamma
            ctx_norm = self.mismatch(S, G, self.R_star, normalized=True)
            ctx_raw = self.raw_mismatch(S, G, self.R_star)

            terms.update({
                "ctx": ctx_norm,
                "ctx_raw": ctx_raw,
                "geo": self.geo(G),
                "rho_micro": np.nan,
                "rho_macro": np.nan,
                "coherence": np.nan,
                "coherence_raw": np.nan,
                "dens_pen": np.nan,
                "regime_code": np.nan,
            })

            energy = (
                self.l_var * terms["var"]
                + self.l_deg * terms["deg"]
                + self.l_ctx * terms["ctx"]
                + self.l_glue * terms["geo"]
                + self.l_carry * terms["carry"]
            )

        return float(energy), terms

    def I_eff(self, S, S_old):
        if not self.Psi(S):
            return float("inf"), None, None, {"n_fiber_valid": 0}

        gammas = self.fiber(S)
        energies = []
        best_val = float("inf")
        best_G = None
        best_terms = None

        for G in gammas:
            val, terms = self.interface_terms(S, G, S_old)
            energies.append(val)
            if val < best_val:
                best_val = val
                best_G = G
                best_terms = terms

        if len(energies) == 0:
            return float("inf"), None, None, {"n_fiber_valid": 0}

        edge_sets = []
        for G in gammas:
            if isinstance(G, dict):
                edge_sets.append(self.edge_set(G["macro"]))
            else:
                edge_sets.append(self.edge_set(G))

        dists = []
        for i in range(len(edge_sets)):
            for j in range(i + 1, len(edge_sets)):
                dists.append(len(edge_sets[i].symmetric_difference(edge_sets[j])))

        stats = {
            "n_fiber_valid": len(energies),
            "fiber_energies": energies,
            "fiber_min": float(np.min(energies)),
            "fiber_mean": float(np.mean(energies)),
            "fiber_std": float(np.std(energies)),
            "fiber_pairwise_edit_mean": float(np.mean(dists)) if len(dists) else 0.0,
        }
        return best_val, best_G, best_terms, stats

    # --------------------------------------------------------
    # vizinhança Theta
    # --------------------------------------------------------
    def neighborhood(self):
        candidates = []
        move_types = []
        nodes = list(self.S.nodes())

        for _ in range(self.K_moves):
            if self.rng.random() < 0.5:
                u, v = self.rng.sample(nodes, 2)
                if not self.S.has_edge(u, v):
                    S2 = copy.deepcopy(self.S)
                    S2.add_edge(u, v)
                    candidates.append(S2)
                    move_types.append("add")
            else:
                if self.S.number_of_edges() > 0:
                    u, v = self.rng.choice(list(self.S.edges()))
                    S2 = copy.deepcopy(self.S)
                    S2.remove_edge(u, v)
                    candidates.append(S2)
                    move_types.append("remove")

        return candidates, move_types

    # --------------------------------------------------------
    # diagnósticos do grafo
    # --------------------------------------------------------
    def graph_diagnostics(self, S):
        degrees = list(dict(S.degree()).values())
        comp_sizes = sorted([len(c) for c in nx.connected_components(S)], reverse=True)
        largest_comp = comp_sizes[0] if comp_sizes else 0
        clustering = nx.average_clustering(S) if S.number_of_nodes() > 2 else 0.0

        try:
            diameter = nx.diameter(S) if nx.is_connected(S) else np.nan
        except Exception:
            diameter = np.nan

        try:
            avg_path = nx.average_shortest_path_length(S) if nx.is_connected(S) else np.nan
        except Exception:
            avg_path = np.nan

        return {
            "deg_max": max(degrees) if degrees else 0,
            "deg_mean": float(np.mean(degrees)) if degrees else 0.0,
            "deg_std": float(np.std(degrees)) if degrees else 0.0,
            "components": nx.number_connected_components(S),
            "largest_comp": largest_comp,
            "diameter": diameter,
            "avg_path": avg_path,
            "clustering": clustering,
            "n_edges": S.number_of_edges(),
        }

    def _record_step(self, t, energy, terms, fiber_stats, graph_stats, best_gap, best_move,
                     n_candidates, n_feasible, n_rejected):
        self.diag["t"].append(t)
        self.diag["I_eff"].append(energy)
        self.diag["deg_max"].append(graph_stats["deg_max"])
        self.diag["deg_mean"].append(graph_stats["deg_mean"])
        self.diag["components"].append(graph_stats["components"])
        self.diag["clustering"].append(graph_stats["clustering"])
        self.diag["fiber_std"].append(fiber_stats.get("fiber_std", np.nan) if fiber_stats else np.nan)
        self.diag["fiber_pairwise_edit_mean"].append(fiber_stats.get("fiber_pairwise_edit_mean", np.nan) if fiber_stats else np.nan)
        self.diag["best_gap"].append(best_gap)

        if terms is not None:
            self.diag["term_ctx_raw"].append(terms.get("ctx_raw", np.nan))
            self.diag["term_ctx"].append(terms.get("ctx", np.nan))
            self.diag["term_ctx_micro"].append(terms.get("ctx_micro", np.nan))
            self.diag["term_ctx_macro"].append(terms.get("ctx_macro", np.nan))
            self.diag["term_coherence"].append(terms.get("coherence", np.nan))
            self.diag["term_dens_pen"].append(terms.get("dens_pen", np.nan))
        else:
            self.diag["term_ctx_raw"].append(np.nan)
            self.diag["term_ctx"].append(np.nan)
            self.diag["term_ctx_micro"].append(np.nan)
            self.diag["term_ctx_macro"].append(np.nan)
            self.diag["term_coherence"].append(np.nan)
            self.diag["term_dens_pen"].append(np.nan)

        self.diag["n_candidates"].append(n_candidates)
        self.diag["n_feasible"].append(n_feasible)
        self.diag["n_rejected"].append(n_rejected)
        self.diag["acceptance_ratio"].append(n_feasible / n_candidates if n_candidates > 0 else np.nan)
        self.diag["best_move"].append(best_move)

    # --------------------------------------------------------
    # dinâmica com termalização
    # --------------------------------------------------------
    def run(self, steps=60, T=0.0):
        """
        T = temperatura.
        T=0.0 -> descida estrita.
        T>0   -> Metropolis-Hastings.
        """
        print(f"=== Simulação EPPQ ({self.context_mode.upper()} Γ) | Temp={T} ===")

        current, _, current_terms, current_fiber_stats = self.I_eff(self.S, self.S)
        self.history.append(current)
        gd = self.graph_diagnostics(self.S)

        self._record_step(
            t=0,
            energy=current,
            terms=current_terms,
            fiber_stats=current_fiber_stats,
            graph_stats=gd,
            best_gap=np.nan,
            best_move="init",
            n_candidates=0,
            n_feasible=0,
            n_rejected=0,
        )

        print(f"t=0 | I_eff={current:.4f} | grau_max={gd['deg_max']} | comp={gd['components']}")

        for t in range(1, steps + 1):
            candidates, move_types = self.neighborhood()

            best_val = float("inf")
            best_S = None
            best_move = None
            best_terms = None
            best_fiber_stats = None

            feasible_vals = []
            feasible = 0
            rejected = 0

            for S2, mtype in zip(candidates, move_types):
                if not self.Psi(S2):
                    rejected += 1
                    continue

                feasible += 1
                val, _, terms, fiber_stats = self.I_eff(S2, self.S)
                feasible_vals.append(val)

                if val < best_val:
                    best_val = val
                    best_S = S2
                    best_move = mtype
                    best_terms = terms
                    best_fiber_stats = fiber_stats

            if len(feasible_vals) == 0:
                print(f"🛑 Nenhum candidato viável em t={t}.")
                break

            feasible_vals = np.array(feasible_vals)
            best_gap = float(np.partition(feasible_vals, 1)[1] - best_val) if len(feasible_vals) >= 2 else np.nan

            # Termalização
            delta_I = best_val - self.history[-1]
            accept = False

            if delta_I < 0:
                accept = True
            else:
                if T > 0:
                    prob = np.exp(-delta_I / T)
                    if self.rng.random() < prob:
                        accept = True
                        best_move = best_move + " (thermal accept)"

            if accept:
                self.S = best_S
                self.history.append(best_val)
                gd_new = self.graph_diagnostics(best_S)
            else:
                best_S = self.S
                best_val = self.history[-1]
                best_move = "reject (thermal)"
                self.history.append(best_val)
                gd_new = self.graph_diagnostics(self.S)

                if T == 0.0:
                    print(f"🛑 Platô de Mosco alcançado em t={t-1}.")
                    break

            self._record_step(
                t=t,
                energy=best_val,
                terms=best_terms,
                fiber_stats=best_fiber_stats,
                graph_stats=gd_new,
                best_gap=best_gap,
                best_move=best_move,
                n_candidates=len(candidates),
                n_feasible=feasible,
                n_rejected=rejected,
            )

            print(
                f"t={t} | I_eff={best_val:.4f} | grau_max={gd_new['deg_max']} | "
                f"comp={gd_new['components']} | mov={best_move} | gap={best_gap:.4f}"
            )

            if len(self.history) >= 2 and abs(self.history[-1] - self.history[-2]) < self.eps_stop and T == 0.0:
                print(f"🛑 Platô de Mosco alcançado em t={t}.")
                break

        print("=== Fim da simulação ===")

    # --------------------------------------------------------
    # outputs
    # --------------------------------------------------------
    def to_dataframe(self):
        return pd.DataFrame(self.diag)

    def summary(self):
        df = self.to_dataframe()
        if len(df) == 0:
            return {}
        return {
            "context_mode": self.context_mode,
            "final_I_eff": float(df["I_eff"].iloc[-1]),
            "final_deg_max": float(df["deg_max"].iloc[-1]),
            "final_components": float(df["components"].iloc[-1]),
            "mean_fiber_std": float(df["fiber_std"].mean(skipna=True)),
            "mean_best_gap": float(df["best_gap"].mean(skipna=True)),
            "mean_ctx_raw": float(df["term_ctx_raw"].mean(skipna=True)) if "term_ctx_raw" in df.columns else np.nan,
            "mean_ctx_norm": float(df["term_ctx"].mean(skipna=True)) if "term_ctx" in df.columns else np.nan,
            "mean_pairwise_gamma_edit": float(df["fiber_pairwise_edit_mean"].mean(skipna=True)),
        }

    # --------------------------------------------------------
    # plots
    # --------------------------------------------------------
    def plot_graph(self, title=None):
        plt.figure(figsize=(9, 7))
        pos = nx.spring_layout(self.S, seed=42)
        degrees = [self.S.degree(n) for n in self.S.nodes()]
        nx.draw(
            self.S,
            pos,
            node_color=degrees,
            cmap=plt.cm.viridis,
            with_labels=True,
            node_size=520,
            font_color="white",
            edge_color="black",
        )
        plt.title(title if title is not None else f"Estado final ({self.context_mode})")
        plt.show()

    def plot_energy_total(self):
        plt.figure(figsize=(9, 4))
        plt.plot(self.diag["t"], self.diag["I_eff"], marker="o")
        plt.xlabel("t")
        plt.ylabel("I_eff")
        plt.title(f"Energia efetiva total ({self.context_mode})")
        plt.grid(True)
        plt.show()

    def plot_energy_terms(self):
        plt.figure(figsize=(11, 6))
        plt.plot(self.diag["t"], self.diag["term_var"], label="var")
        plt.plot(self.diag["t"], self.diag["term_deg"], label="deg")
        plt.plot(self.diag["t"], self.diag["term_carry"], label="carry")

        if self.context_mode == "two_layer":
            plt.plot(self.diag["t"], self.diag["term_ctx_micro"], label="ctx_micro")
            plt.plot(self.diag["t"], self.diag["term_ctx_macro"], label="ctx_macro")
            plt.plot(self.diag["t"], self.diag["term_coherence"], label="coherence")
            plt.plot(self.diag["t"], self.diag["term_dens_pen"], label="dens_pen")
        else:
            plt.plot(self.diag["t"], self.diag["term_ctx"], label="ctx")

        plt.xlabel("t")
        plt.ylabel("valor do termo")
        plt.title(f"Decomposição da energia por termo ({self.context_mode})")
        plt.legend()
        plt.grid(True)
        plt.show()

    def plot_fiber_stats(self):
        plt.figure(figsize=(11, 6))
        plt.plot(self.diag["t"], self.diag["fiber_min"], label="min")
        plt.plot(self.diag["t"], self.diag["fiber_mean"], label="mean")
        plt.plot(self.diag["t"], self.diag["fiber_std"], label="std")
        plt.xlabel("t")
        plt.ylabel("estatística da fibra")
        plt.title(f"Estatísticas da fibra Γ ({self.context_mode})")
        plt.legend()
        plt.grid(True)
        plt.show()

    def plot_graph_stats(self):
        fig, axs = plt.subplots(2, 2, figsize=(12, 9))

        axs[0, 0].plot(self.diag["t"], self.diag["deg_max"], marker="o")
        axs[0, 0].set_title("Grau máximo")
        axs[0, 0].grid(True)

        axs[0, 1].plot(self.diag["t"], self.diag["components"], marker="o")
        axs[0, 1].set_title("Componentes conexas")
        axs[0, 1].grid(True)

        axs[1, 0].plot(self.diag["t"], self.diag["clustering"], marker="o")
        axs[1, 0].set_title("Clustering médio")
        axs[1, 0].grid(True)

        axs[1, 1].plot(self.diag["t"], self.diag["best_gap"], marker="o")
        axs[1, 1].set_title("Gap entre melhor e 2º melhor")
        axs[1, 1].grid(True)

        plt.tight_layout()
        plt.show()

# ============================================================
# RUNNER ÚNICO
# ============================================================

def run_context_comparison(
    N=30,
    D_star=4,
    steps=60,
    seed=7,
    K_moves=50,
    K_fiber_local=10,
    K_fiber_global=1,
    K_fiber_two_layer=5,
    eps_stop=1e-3,
    L_ctx=5,
    rho_star=0.18,
    p_local_add=0.20,
    macro_hop=2,
    macro_rounds=1,
    T=0.0,
    start_graph_mode="path",
):
    base_graph = build_start_graph(N, mode=start_graph_mode, seed=seed)

    sim_local = EPPQContextualSimulator(
        N=N,
        D_star=D_star,
        R_star=2,
        context_mode="local",
        seed=seed,
        K_moves=K_moves,
        K_fiber_local=K_fiber_local,
        K_fiber_global=K_fiber_global,
        K_fiber_two_layer=K_fiber_two_layer,
        eps_stop=eps_stop,
        L_ctx=L_ctx,
        rho_star=rho_star,
        p_local_add=p_local_add,
        macro_hop=macro_hop,
        macro_rounds=macro_rounds,
        start_graph=base_graph,
    )

    sim_global = EPPQContextualSimulator(
        N=N,
        D_star=D_star,
        R_star=2,
        context_mode="global",
        seed=seed,
        K_moves=K_moves,
        K_fiber_local=K_fiber_local,
        K_fiber_global=K_fiber_global,
        K_fiber_two_layer=K_fiber_two_layer,
        eps_stop=eps_stop,
        L_ctx=L_ctx,
        rho_star=rho_star,
        p_local_add=p_local_add,
        macro_hop=macro_hop,
        macro_rounds=macro_rounds,
        start_graph=base_graph,
    )

    sim_two = EPPQContextualSimulator(
        N=N,
        D_star=D_star,
        R_star=2,
        context_mode="two_layer",
        seed=seed,
        K_moves=K_moves,
        K_fiber_local=K_fiber_local,
        K_fiber_global=K_fiber_global,
        K_fiber_two_layer=K_fiber_two_layer,
        eps_stop=eps_stop,
        L_ctx=L_ctx,
        rho_star=rho_star,
        p_local_add=p_local_add,
        macro_hop=macro_hop,
        macro_rounds=macro_rounds,
        start_graph=base_graph,
    )

    print("\n==============================")
    print("RUN: LOCAL CONTEXT")
    print("==============================")
    sim_local.plot_graph("Estado inicial (local)")
    sim_local.run(steps=steps, T=T)
    sim_local.plot_graph(f"Estado final (local) | T={T}")
    sim_local.plot_energy_total()

    print("\n==============================")
    print("RUN: GLOBAL CONTEXT")
    print("==============================")
    sim_global.run(steps=steps, T=T)
    sim_global.plot_graph(f"Estado final (global) | T={T}")
    sim_global.plot_energy_total()

    print("\n==============================")
    print("RUN: TWO-LAYER CONTEXT")
    print("==============================")
    sim_two.run(steps=steps, T=T)
    sim_two.plot_graph(f"Estado final (two-layer) | T={T}")
    sim_two.plot_energy_total()

    df_local = sim_local.to_dataframe()
    df_global = sim_global.to_dataframe()
    df_two = sim_two.to_dataframe()

    plt.figure(figsize=(10, 5))
    plt.plot(df_local["t"], df_local["I_eff"], label="local")
    plt.plot(df_global["t"], df_global["I_eff"], label="global")
    plt.plot(df_two["t"], df_two["I_eff"], label="two-layer")
    plt.xlabel("t")
    plt.ylabel("I_eff")
    plt.title(f"Comparação da energia efetiva (Temperatura T={T})")
    plt.legend()
    plt.grid(True)
    plt.show()

    return sim_local, sim_global, sim_two

# ============================================================
# BATERIA COMPLETA (SEEDS x TEMPERATURES)
# ============================================================

def run_full_battery():
    rows = []
    all_runs = {}

    for seed in SEEDS:
        for T in TEMPERATURES:
            print("\n======================================")
            print(f"RUN | seed={seed} | T={T}")
            print("======================================")

            sim_local, sim_global, sim_two = run_context_comparison(
                N=N,
                D_star=D_star,
                steps=STEPS,
                seed=seed,
                K_moves=K_moves,
                K_fiber_local=K_fiber_local,
                K_fiber_global=K_fiber_global,
                K_fiber_two_layer=K_fiber_two_layer,
                eps_stop=eps_stop,
                L_ctx=L_ctx,
                rho_star=rho_star,
                p_local_add=p_local_add,
                macro_hop=macro_hop,
                macro_rounds=macro_rounds,
                T=T,
                start_graph_mode=START_GRAPH_MODE,
            )

            for mode, sim in [("local", sim_local), ("global", sim_global), ("two_layer", sim_two)]:
                df = sim.to_dataframe().copy()
                metrics = compute_thermal_metrics(df)

                row = {
                    "seed": seed,
                    "T": T,
                    "mode": mode,
                    "n_steps": len(df),
                    "deg_max_final": int(df["deg_max"].iloc[-1]) if len(df) else np.nan,
                    "components_final": int(df["components"].iloc[-1]) if len(df) else np.nan,
                    **metrics,
                }
                rows.append(row)

                all_runs[(seed, T, mode)] = {
                    "sim": sim,
                    "df": df,
                    "metrics": metrics,
                }

    df_results = pd.DataFrame(rows)

    print("\n===== RESULTADOS AGREGADOS =====")
    display(df_results.sort_values(["mode", "T", "seed"]).reset_index(drop=True))

    summary = (
        df_results
        .groupby(["mode", "T"], as_index=False)
        .agg(
            E_mean_tail_mean=("E_mean_tail", "mean"),
            E_mean_tail_std=("E_mean_tail", "std"),
            E_std_tail_mean=("E_std_tail", "mean"),
            uphill_rate_total_mean=("uphill_rate_total", "mean"),
            uphill_rate_tail_mean=("uphill_rate_tail", "mean"),
            tail_slope_mean=("tail_slope", "mean"),
            deg_max_final_mean=("deg_max_final", "mean"),
            components_final_mean=("components_final", "mean"),
        )
    )

    print("\n===== SUMMARY POR MODE E TEMPERATURA =====")
    display(summary.sort_values(["mode", "T"]).reset_index(drop=True))

    mode_order = ["local", "global", "two_layer"]

    plt.figure(figsize=(11, 5))
    for mode in mode_order:
        sub = summary[summary["mode"] == mode].sort_values("T")
        y = sub["E_mean_tail_mean"].to_numpy(dtype=float)
        yerr = sub["E_mean_tail_std"].fillna(0.0).to_numpy(dtype=float)
        plt.errorbar(sub["T"], y, yerr=yerr, marker="o", capsize=4, label=mode)
    plt.xlabel("Temperatura T")
    plt.ylabel("Energia média no platô")
    plt.title("Termalização EPPQ — energia média de equilíbrio vs temperatura")
    plt.grid(True)
    plt.legend()
    plt.show()

    plt.figure(figsize=(11, 5))
    for mode in mode_order:
        sub = summary[summary["mode"] == mode].sort_values("T")
        plt.plot(sub["T"], sub["uphill_rate_tail_mean"], marker="o", label=mode)
    plt.xlabel("Temperatura T")
    plt.ylabel("Taxa média de aceitação de subida")
    plt.title("Exploração térmica — aceitação de movimentos energéticos ascendentes")
    plt.grid(True)
    plt.legend()
    plt.show()

    plt.figure(figsize=(11, 5))
    for mode in mode_order:
        sub = summary[summary["mode"] == mode].sort_values("T")
        plt.plot(sub["T"], sub["E_std_tail_mean"], marker="o", label=mode)
    plt.xlabel("Temperatura T")
    plt.ylabel("Desvio-padrão médio no platô")
    plt.title("Flutuação térmica no regime assintótico")
    plt.grid(True)
    plt.legend()
    plt.show()

    return df_results, summary, all_runs

# ============================================================
# EXECUÇÃO
# ============================================================

if RUN_FULL_BATTERY:
    df_results, summary, all_runs = run_full_battery()

    # Exemplo visual padronizado: escolhe seed/T do SAMPLE
    key = (SAMPLE_SEED, SAMPLE_T, "local")
    if key in all_runs:
        sim_local = all_runs[(SAMPLE_SEED, SAMPLE_T, "local")]["sim"]
        sim_global = all_runs[(SAMPLE_SEED, SAMPLE_T, "global")]["sim"]
        sim_two = all_runs[(SAMPLE_SEED, SAMPLE_T, "two_layer")]["sim"]

        df_local = sim_local.to_dataframe()
        df_global = sim_global.to_dataframe()
        df_two = sim_two.to_dataframe()

        plt.figure(figsize=(11, 5))
        plt.plot(df_local["t"], df_local["I_eff"], label="local")
        plt.plot(df_global["t"], df_global["I_eff"], label="global")
        plt.plot(df_two["t"], df_two["I_eff"], label="two-layer")
        plt.xlabel("t")
        plt.ylabel("I_eff")
        plt.title(f"Trajetórias temporais de I_eff | T={SAMPLE_T}")
        plt.legend()
        plt.grid(True)
        plt.show()

        sim_two.plot_graph(f"Estado final (two-layer) | T={SAMPLE_T}")
else:
    sim_local, sim_global, sim_two = run_context_comparison(
        N=N,
        D_star=D_star,
        steps=STEPS,
        seed=SAMPLE_SEED,
        K_moves=K_moves,
        K_fiber_local=K_fiber_local,
        K_fiber_global=K_fiber_global,
        K_fiber_two_layer=K_fiber_two_layer,
        eps_stop=eps_stop,
        L_ctx=L_ctx,
        rho_star=rho_star,
        p_local_add=p_local_add,
        macro_hop=macro_hop,
        macro_rounds=macro_rounds,
        T=SAMPLE_T,
        start_graph_mode=START_GRAPH_MODE,
    )

    df_local = sim_local.to_dataframe()
    df_global = sim_global.to_dataframe()
    df_two = sim_two.to_dataframe()

    display(df_local.head())
    display(df_global.head())
    display(df_two.head())